### ISSUE TITLE
Incomplete singularity definition file 

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/DRPreter#2]
Followed instructions but definition file is empty.

**Comment by mcnaughtonadm** [comment]
First attempt of the singularity definition file is addressed in 9fae27e .

**Comment by mcnaughtonadm** [comment]
Modifications made in c417b7a that fix some problems with downloading packages. Was able to create a .sif from this.

**Comment by wilke** [comment]
sif file is building - closing
